apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadbpv
  labels:
    app: wordpress
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
     namespace: wordpress
     name: data-wordpress-mariadb-0
  hostPath:
    path: "/bitnami/mariadb"
