apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpresspv
  labels:
    app: wordpress
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
     namespace: wordpress
     name: wordpress
  hostPath:
    path: "/bitnami/wordpress"
